In [2]:
import train_test_generation
from keras.layers import Dense,Conv2D,MaxPooling2D,UpSampling2D
from keras import Input, Model
from keras.datasets import mnist
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras import regularizers
import keras
import pandas as pd

62.5


In [2]:
#features, output = train_test_generation.generatefinaldf(10**5, 'ML', 90)

C:\Users\User\Documents\Freshman\Build 2022\build2022hackathon\ML Models\train_test_generation.py:525: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[article][ite] = bool(random.getrandbits(1))
C:\Users\User\anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [3]:
features = pd.read_csv("features.csv")
output = pd.read_csv("output.csv")

In [4]:
features.tail()

temperature  humidity  precipitation  windspeed  age  weight  height  \
99995           10         8             94         18   38    48.0   131.0   
99996           17        85             77          6   45    76.0   173.0   
99997           21        78             36         40   31    48.0   174.0   
99998          -15        42             89         34   46    38.0   113.0   
99999            5        88             78         39   37    95.0   134.0   

       sex  fatpercentage        bmi  cold_resistance  scoring_difference  \
99995    1      36.904478  27.970398            100.0            0.000000   
99996    1      35.422117  25.393431             80.0            0.000000   
99997    1      20.754970  15.854142             77.5            0.000000   
99998    0      30.091489  29.759574             90.0           -6.033333   
99999    1      66.598528  52.907106            100.0           -3.666667   

       adjusted_cold_resistance  preference_factor  
99995                     98.00                 98  
99996                     76.80                 96  
99997                     79.05                102  
99998                     92.70                103  
99999                     97.00                 97

In [5]:
output.tail()

thermal  hoodie  fleece   wool  light_down  thick_down  wind_breaker  \
99995     True    True    True  False        True        True         False   
99996     True    True    True   True        True       False         False   
99997     True    True    True   True       False        True          True   
99998    False   False   False  False        True        True         False   
99999    False   False    True  False        True       False          True   

       umbrella  winter_boots  user_feedback  
99995     False          True              1  
99996      True         False              1  
99997      True         False              1  
99998     False          True              0  
99999     False         False              1

NameError: name 'output' is not defined

In [6]:
#features.to_csv("features.csv", index=False)
#output.to_csv("output.csv", index=False)

In [6]:
user_params_df = features[['age', 'weight', 'height', 'sex', 'fatpercentage', 'bmi']]

In [7]:
user_params_df.head()

age      weight      height  sex  fatpercentage        bmi
0   59   76.350691  165.034328    1      41.809198  28.032665
1   24   83.566165  176.487951    0      21.514493  26.828745
2   24   96.348209  178.793425    0      25.487776  30.139813
3   25  106.733295  179.147332    0      29.458047  33.256706
4   29   68.463140  163.715886    1      31.921830  25.543192

In [8]:
#https://www.analyticsvidhya.com/blog/2021/06/complete-guide-on-how-to-use-autoencoders-in-python/

In [9]:
#num = user_params_df.values
#num = tf.convert_to_tensor(num)

In [10]:
from sklearn.preprocessing import MinMaxScaler 
X = MinMaxScaler().fit_transform(user_params_df)

In [11]:
#https://www.geeksforgeeks.org/ml-classifying-data-using-an-auto-encoder/

In [12]:
input_layer = Input(shape =(X.shape[1], ))

In [13]:
#building the autoencoder network
encoded = Dense(100, activation ='linear',
                activity_regularizer = regularizers.l1(10e-5))(input_layer)
encoded = Dense(50, activation ='linear',
                activity_regularizer = regularizers.l1(10e-5))(encoded)
encoded = Dense(25, activation ='linear',
                activity_regularizer = regularizers.l1(10e-5))(encoded)
encoded = Dense(12, activation ='linear',
                activity_regularizer = regularizers.l1(10e-5))(encoded)
encoded = Dense(4, activation ='linear')(encoded)
  
# Building the Decoder network
decoded = Dense(12, activation ='linear')(encoded)
decoded = Dense(25, activation ='linear')(decoded)
decoded = Dense(50, activation ='linear')(decoded)
decoded = Dense(100, activation ='linear')(decoded)
  
# Building the Output Layer
output_layer = Dense(X.shape[1], activation ='relu')(decoded)
output_layer = Dense(X.shape[1], activation ='relu')(decoded)

In [14]:
autoencoder = Model(input_layer, output_layer)
autoencoder.compile(optimizer ="adam", loss ="binary_crossentropy" , metrics=['accuracy'])

In [15]:
autoencoder.fit(X, X, 
                batch_size = 20, epochs = 25, 
                shuffle = True, validation_split = 0.20)

Epoch 1/25
4000/4000 [==============================] - 6s 1ms/step - loss: 1.1125 - accuracy: 0.9390 - val_loss: 0.5979 - val_accuracy: 0.8618
Epoch 2/25
4000/4000 [==============================] - 5s 1ms/step - loss: 0.4894 - accuracy: 0.9642 - val_loss: 0.5406 - val_accuracy: 0.9167
Epoch 3/25
4000/4000 [==============================] - 5s 1ms/step - loss: 0.4917 - accuracy: 0.9456 - val_loss: 0.8027 - val_accuracy: 0.8043
Epoch 4/25
4000/4000 [==============================] - 5s 1ms/step - loss: 0.5033 - accuracy: 0.9463 - val_loss: 0.5594 - val_accuracy: 0.9030
Epoch 5/25
4000/4000 [==============================] - 5s 1ms/step - loss: 0.4937 - accuracy: 0.9395 - val_loss: 0.7396 - val_accuracy: 0.8277
Epoch 6/25
4000/4000 [==============================] - 5s 1ms/step - loss: 0.4961 - accuracy: 0.9319 - val_loss: 0.7028 - val_accuracy: 0.8498
Epoch 7/25
4000/4000 [==============================] - 5s 1ms/step - loss: 0.4890 - accuracy: 0.9599 - val_loss: 0.6453 - val_accuracy:

In [18]:
# Extracting the embedding
encoder = keras.Model(input_layer, encoded)
encoder.save('encoder.h5', overwrite = True)





encoded_r = encoder.predict(X)
print(encoded_r)

[[-0.24239564  0.75530356 -0.17539549 -0.405838  ]
 [ 0.3810345  -0.25795838  0.01292167 -0.04001822]
 [ 0.40121487 -0.2610022   0.04401319  0.00557351]
 ...
 [-0.22865078  0.11329341 -0.1041531  -0.08893278]
 [ 0.21686009  0.26808918 -0.53344274 -0.63062435]
 [-0.17266461  0.15962586 -0.38688743 -0.052258  ]]


In [ ]:

# Transforming to a CSV file using pandas

df = pd.DataFrame(encoded_r, columns = ["Attribute 1", "Attribute 2", "Attribute 3", "Attribute 4"])
print(df)

In [5]:
import tensorflow as tf
encoder = tf.keras.models.load_model("encoder.h5", compile = False)
test_output = encoder.predict([[59, 76.350691, 165.034328, 1, 41.809198, 28.032665]])


InternalError:  Attempting to perform BLAS operation using StreamExecutor without BLAS support
	 [[node model_3/dense/MatMul
 (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\core\dense.py:199)
]] [Op:__inference_predict_function_579]

Errors may have originated from an input operation.
Input Source operations connected to node model_3/dense/MatMul:
In[0] IteratorGetNext (defined at C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py:1610)	
In[1] model_3/dense/MatMul/ReadVariableOp:

Operation defined at: (most recent call last)
>>>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
>>>     return _run_code(code, main_globals, None,
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
>>>     app.start()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
>>>     self.io_loop.start()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 570, in run_forever
>>>     self._run_once()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1859, in _run_once
>>>     handle._run()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 81, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
>>>     lambda f: self._run_callback(functools.partial(callback, future))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
>>>     ret = callback()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
>>>     self.run()
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
>>>     yielded = self.gen.send(value)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
>>>     yield gen.maybe_future(dispatch(*args))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
>>>     yielded = next(result)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
>>>     yield gen.maybe_future(handler(stream, idents, msg))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
>>>     yielded = next(result)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
>>>     self.do_execute(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
>>>     yielded = next(result)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2877, in run_cell
>>>     result = self._run_cell(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2923, in _run_cell
>>>     return runner(coro)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
>>>     coro.send(None)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3146, in run_cell_async
>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3338, in run_ast_nodes
>>>     if (await self.run_code(code, result,  async_=asy)):
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "<ipython-input-5-c978a290e085>", line 3, in <module>
>>>     test_output = encoder.predict([[59, 76.350691, 165.034328, 1, 41.809198, 28.032665]])
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1789, in predict
>>>     tmp_batch_outputs = self.predict_function(iterator)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1621, in predict_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1611, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1604, in run_step
>>>     outputs = model.predict_step(data)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1572, in predict_step
>>>     return self(x, training=False)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\functional.py", line 451, in call
>>>     return self._run_internal_graph(
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
>>>     outputs = node.layer(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\ProgramData\Anaconda3\lib\site-packages\keras\layers\core\dense.py", line 199, in call
>>>     outputs = tf.matmul(a=inputs, b=self.kernel)
>>> 

In [ ]:
df.to_csv("R_values.csv", index=False)